# 公開するページのURL
baseURL = "https://tachibana-mayumi.github.io/tachibana-mayumi-blog"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "株式会社エナジー〇〇で働く立花真由美の技術メモ：alohaなハワイに逃げ出したい"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "立花真由美"
    bio = "株式会社エナジー〇〇で働く元文系のSEの奮闘メモ。alohaなハワイへ逃げ出して、すべての仕事を投げてしまいたい午後"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "立花真由美の技術メモ"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#e22d30"

# SNS等のユーザー名
[Params.widgets.social]
  github = "tachibana-mayumi"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

