# 公開するページのURL
baseURL = "https://tachibana-mayumi.github.io/tachibana-mayumi-blog"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "立花真由美の技術メモ"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "立花真由美"
    bio = "デザイナーから技術系に仕事が変わってしまったOLの奮闘メモ"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#e22d30"

# SNS等のユーザー名
[Params.widgets.social]
  github = "tachibana-mayumi"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

